import { Recipe } from '@/types';

export const SEED_RECIPES: Recipe[] = [
  {
    id: 'seed-001',
    title: 'Spaghetti Carbonara',
    description: 'Ein klassisches römisches Pasta-Gericht mit Ei, Pecorino und Guanciale.',
    duration_min: 25,
    servings: 4,
    difficulty: 'mittel',
    rating: 5,
    notes: 'Kein Sahne! Echte Carbonara wird nur mit Ei und Käse gebunden.',
    ingredients: [
      { id: 'si-001', amount: 400, unit: 'g', name: 'Spaghetti', group: 'Nudeln & Reis' },
      { id: 'si-002', amount: 150, unit: 'g', name: 'Guanciale', group: 'Kühlregal' },
      { id: 'si-003', amount: 4, unit: 'Stk', name: 'Eigelb', group: 'Kühlregal' },
      { id: 'si-004', amount: 1, unit: 'Stk', name: 'ganzes Ei', group: 'Kühlregal' },
      { id: 'si-005', amount: 100, unit: 'g', name: 'Pecorino Romano', group: 'Kühlregal' },
      { id: 'si-006', amount: 1, unit: 'TL', name: 'schwarzer Pfeffer', group: 'Gewürze' },
      { id: 'si-007', amount: 1, unit: 'Prise', name: 'Salz', group: 'Gewürze' },
    ],
    steps: [
      { id: 'ss-001', order: 1, title: 'Wasser kochen', text: 'Reichlich Salzwasser in einem großen Topf zum Kochen bringen.' },
      { id: 'ss-002', order: 2, title: 'Guanciale anbraten', text: 'Guanciale in Streifen schneiden und in einer Pfanne ohne Öl knusprig ausbraten. Beiseitestellen.', timer_min: 5 },
      { id: 'ss-003', order: 3, title: 'Eier-Käse-Mischung', text: 'Eigelb, ganzes Ei und geriebenen Pecorino vermengen. Mit viel schwarzem Pfeffer würzen.' },
      { id: 'ss-004', order: 4, title: 'Pasta kochen', text: 'Spaghetti nach Packungsanweisung al dente kochen. 1 Tasse Kochwasser aufbewahren.', timer_min: 10 },
      { id: 'ss-005', order: 5, title: 'Alles verbinden', text: 'Heiße Pasta in die Pfanne mit Guanciale geben (Hitze aus). Eier-Käse-Mischung und etwas Kochwasser einrühren, bis eine cremige Sauce entsteht.' },
    ],
    created_at: '2024-01-10T10:00:00.000Z',
    updated_at: '2024-01-10T10:00:00.000Z',
  },
  {
    id: 'seed-002',
    title: 'Griechischer Bauernsalat',
    description: 'Frischer mediterraner Salat mit Feta, Oliven und knackigem Gemüse.',
    duration_min: 15,
    servings: 2,
    difficulty: 'einfach',
    rating: 4,
    notes: 'Beste Qualität mit reifen Tomaten und gutem Olivenöl.',
    ingredients: [
      { id: 'si-010', amount: 3, unit: 'Stk', name: 'Tomaten', group: 'Gemüse' },
      { id: 'si-011', amount: 1, unit: 'Stk', name: 'Gurke', group: 'Gemüse' },
      { id: 'si-012', amount: 1, unit: 'Stk', name: 'rote Zwiebel', group: 'Gemüse' },
      { id: 'si-013', amount: 1, unit: 'Stk', name: 'grüne Paprika', group: 'Gemüse' },
      { id: 'si-014', amount: 200, unit: 'g', name: 'Feta-Käse', group: 'Kühlregal' },
      { id: 'si-015', amount: 80, unit: 'g', name: 'schwarze Kalamata-Oliven', group: 'Konserven' },
      { id: 'si-016', amount: 4, unit: 'EL', name: 'Olivenöl', group: 'Öle & Essig' },
      { id: 'si-017', amount: 1, unit: 'TL', name: 'Oregano (getrocknet)', group: 'Gewürze' },
      { id: 'si-018', amount: 1, unit: 'Prise', name: 'Salz & Pfeffer', group: 'Gewürze' },
    ],
    steps: [
      { id: 'ss-010', order: 1, title: 'Gemüse vorbereiten', text: 'Tomaten und Gurke in grobe Stücke schneiden. Zwiebel in dünne Ringe, Paprika in Streifen schneiden.' },
      { id: 'ss-011', order: 2, title: 'Dressing anrühren', text: 'Olivenöl, Salz, Pfeffer und Oregano in einer Schüssel vermengen.' },
      { id: 'ss-012', order: 3, title: 'Salat schichten', text: 'Gemüse auf einer Platte anrichten. Oliven darüber verteilen. Feta als ganzes Stück obenauf legen.' },
      { id: 'ss-013', order: 4, title: 'Dressing verteilen', text: 'Dressing gleichmäßig über den Salat träufeln. Sofort servieren.' },
    ],
    created_at: '2024-02-05T08:00:00.000Z',
    updated_at: '2024-02-05T08:00:00.000Z',
  },
  {
    id: 'seed-003',
    title: 'Kartoffelsuppe mit Würstchen',
    description: 'Wärmende, herzhafte Kartoffelsuppe – ein echter Klassiker der deutschen Küche.',
    duration_min: 45,
    servings: 6,
    difficulty: 'einfach',
    rating: 4,
    notes: 'Schmeckt am nächsten Tag noch besser. Kann problemlos eingefroren werden.',
    ingredients: [
      { id: 'si-020', amount: 1000, unit: 'g', name: 'Kartoffeln', group: 'Gemüse' },
      { id: 'si-021', amount: 2, unit: 'Stk', name: 'Möhren', group: 'Gemüse' },
      { id: 'si-022', amount: 1, unit: 'Stk', name: 'Sellerie-Stange', group: 'Gemüse' },
      { id: 'si-023', amount: 1, unit: 'Stk', name: 'Zwiebel', group: 'Gemüse' },
      { id: 'si-024', amount: 2, unit: 'Stk', name: 'Knoblauchzehen', group: 'Gemüse' },
      { id: 'si-025', amount: 1, unit: 'l', name: 'Gemüsebrühe', group: 'Konserven' },
      { id: 'si-026', amount: 4, unit: 'Stk', name: 'Wiener Würstchen', group: 'Kühlregal' },
      { id: 'si-027', amount: 2, unit: 'EL', name: 'Butter', group: 'Kühlregal' },
      { id: 'si-028', amount: 1, unit: 'Bund', name: 'Petersilie', group: 'Gemüse' },
      { id: 'si-029', amount: 1, unit: 'Prise', name: 'Majoran', group: 'Gewürze' },
    ],
    steps: [
      { id: 'ss-020', order: 1, title: 'Gemüse vorbereiten', text: 'Kartoffeln schälen und würfeln. Möhren und Sellerie in Scheiben schneiden. Zwiebel und Knoblauch fein hacken.' },
      { id: 'ss-021', order: 2, title: 'Andünsten', text: 'Butter in einem großen Topf erhitzen. Zwiebel und Knoblauch glasig dünsten.', timer_min: 3 },
      { id: 'ss-022', order: 3, title: 'Suppe kochen', text: 'Kartoffeln, Möhren und Sellerie hinzufügen. Brühe angießen. Aufkochen und 20 Minuten köcheln lassen.', timer_min: 20 },
      { id: 'ss-023', order: 4, title: 'Teilweise pürieren', text: 'Etwa ein Drittel der Suppe mit dem Stabmixer pürieren, damit sie cremig wird, aber noch Stücke hat.' },
      { id: 'ss-024', order: 5, title: 'Würstchen erwärmen', text: 'Würstchen in Scheiben schneiden, in die Suppe geben und 5 Minuten mitköcheln. Mit Majoran, Salz und Pfeffer abschmecken.', timer_min: 5 },
      { id: 'ss-025', order: 6, title: 'Servieren', text: 'In tiefen Tellern anrichten und mit frisch gehackter Petersilie garnieren.' },
    ],
    created_at: '2024-03-12T12:00:00.000Z',
    updated_at: '2024-03-12T12:00:00.000Z',
  },
  {
    id: 'seed-004',
    title: 'Schokoladen-Bananenbrot',
    description: 'Saftiges Bananenbrot mit Schokoladenstückchen – perfekt für überreife Bananen.',
    duration_min: 70,
    servings: 8,
    difficulty: 'mittel',
    rating: 5,
    notes: 'Die Bananen sollten wirklich sehr reif (schwarz-braun) sein für maximale Süße.',
    ingredients: [
      { id: 'si-030', amount: 3, unit: 'Stk', name: 'überreife Bananen', group: 'Obst' },
      { id: 'si-031', amount: 200, unit: 'g', name: 'Mehl', group: 'Backzutaten' },
      { id: 'si-032', amount: 100, unit: 'g', name: 'Zucker', group: 'Backzutaten' },
      { id: 'si-033', amount: 80, unit: 'g', name: 'Butter', group: 'Kühlregal' },
      { id: 'si-034', amount: 2, unit: 'Stk', name: 'Eier', group: 'Kühlregal' },
      { id: 'si-035', amount: 1, unit: 'TL', name: 'Backpulver', group: 'Backzutaten' },
      { id: 'si-036', amount: 0.5, unit: 'TL', name: 'Natron', group: 'Backzutaten' },
      { id: 'si-037', amount: 1, unit: 'Prise', name: 'Salz', group: 'Backzutaten' },
      { id: 'si-038', amount: 100, unit: 'g', name: 'Schokoladenstückchen', group: 'Backzutaten' },
      { id: 'si-039', amount: 1, unit: 'TL', name: 'Vanilleextrakt', group: 'Backzutaten' },
    ],
    steps: [
      { id: 'ss-030', order: 1, title: 'Ofen vorheizen', text: 'Backofen auf 175 °C Ober-/Unterhitze vorheizen. Eine Kastenform (ca. 25 cm) einfetten und mit Mehl bestäuben.' },
      { id: 'ss-031', order: 2, title: 'Bananen zerdrücken', text: 'Bananen in einer großen Schüssel mit einer Gabel gründlich zerdrücken, bis eine glatte Masse entsteht.' },
      { id: 'ss-032', order: 3, title: 'Feuchte Zutaten', text: 'Butter schmelzen und zusammen mit Eiern, Zucker und Vanilleextrakt zu den Bananen geben. Gut verrühren.' },
      { id: 'ss-033', order: 4, title: 'Trockene Zutaten', text: 'Mehl, Backpulver, Natron und Salz in einer separaten Schüssel mischen. In die Bananenmasse sieben und nur kurz unterrühren (nicht übermischen!).' },
      { id: 'ss-034', order: 5, title: 'Schokolade einfalten', text: 'Schokoladenstückchen unter den Teig heben. In die vorbereitete Form füllen.' },
      { id: 'ss-035', order: 6, title: 'Backen', text: 'Im vorgeheizten Ofen 55–60 Minuten backen. Stäbchenprobe: kein Teig darf haften. Falls nötig, mit Alufolie abdecken.', timer_min: 60 },
    ],
    created_at: '2024-04-18T09:00:00.000Z',
    updated_at: '2024-04-18T09:00:00.000Z',
  },
  {
    id: 'seed-005',
    title: 'Avocado-Toast mit pochiertem Ei',
    description: 'Cremiger Avocado-Aufstrich auf geröstetem Brot, gekrönt mit einem perfekten pochierten Ei.',
    duration_min: 20,
    servings: 2,
    difficulty: 'mittel',
    rating: 4,
    notes: 'Ein Schuss Essig im Kochwasser hilft, das Ei zusammenzuhalten.',
    ingredients: [
      { id: 'si-040', amount: 2, unit: 'Stk', name: 'Avocados (reif)', group: 'Obst' },
      { id: 'si-041', amount: 4, unit: 'Scheibe', name: 'Sauerteigbrot', group: 'Brot & Backwaren' },
      { id: 'si-042', amount: 2, unit: 'Stk', name: 'Eier', group: 'Kühlregal' },
      { id: 'si-043', amount: 1, unit: 'Stk', name: 'Zitrone', group: 'Obst' },
      { id: 'si-044', amount: 1, unit: 'Prise', name: 'Chiliflocken', group: 'Gewürze' },
      { id: 'si-045', amount: 1, unit: 'Prise', name: 'Salz & Pfeffer', group: 'Gewürze' },
      { id: 'si-046', amount: 1, unit: 'EL', name: 'Weißweinessig', group: 'Öle & Essig' },
    ],
    steps: [
      { id: 'ss-040', order: 1, title: 'Brot toasten', text: 'Brotscheiben im Toaster oder in der Pfanne goldbraun rösten.' },
      { id: 'ss-041', order: 2, title: 'Avocado-Creme', text: 'Avocados halbieren, Kern entfernen, Fruchtfleisch in eine Schüssel geben. Mit Zitronensaft, Salz und Pfeffer würzen und grob zerdrücken.' },
      { id: 'ss-042', order: 3, title: 'Wasser vorbereiten', text: 'Wasser in einem kleinen Topf zum sanften Sieden bringen (nicht kochen!). Essig hinzufügen.' },
      { id: 'ss-043', order: 4, title: 'Eier pochieren', text: 'Jedes Ei einzeln in eine Tasse schlagen. Mit einem Löffel einen Strudel im Wasser erzeugen und das Ei hineingleiten lassen. 3–4 Minuten pochieren.', timer_min: 4 },
      { id: 'ss-044', order: 5, title: 'Anrichten', text: 'Avocado-Creme auf die Brotscheiben streichen. Pochiertes Ei darauflegen. Mit Chiliflocken und etwas Salz garnieren.' },
    ],
    created_at: '2024-05-22T07:30:00.000Z',
    updated_at: '2024-05-22T07:30:00.000Z',
  },
  {
    id: 'seed-006',
    title: 'Hähnchen-Tikka-Masala',
    description: 'Zartes, würziges Hähnchen in einer cremigen Tomatensauce – eines der beliebtesten Currys weltweit.',
    duration_min: 55,
    servings: 4,
    difficulty: 'aufwändig',
    rating: 5,
    notes: 'Das Hähnchen mindestens 30 Min. oder über Nacht marinieren für maximalen Geschmack.',
    ingredients: [
      { id: 'si-050', amount: 700, unit: 'g', name: 'Hähnchenbrustfilet', group: 'Fleisch & Fisch' },
      { id: 'si-051', amount: 150, unit: 'g', name: 'Joghurt (Vollmilch)', group: 'Kühlregal' },
      { id: 'si-052', amount: 2, unit: 'TL', name: 'Tikka-Masala-Gewürzmischung', group: 'Gewürze' },
      { id: 'si-053', amount: 1, unit: 'Stk', name: 'große Zwiebel', group: 'Gemüse' },
      { id: 'si-054', amount: 3, unit: 'Stk', name: 'Knoblauchzehen', group: 'Gemüse' },
      { id: 'si-055', amount: 2, unit: 'cm', name: 'frischer Ingwer', group: 'Gemüse' },
      { id: 'si-056', amount: 400, unit: 'g', name: 'stückige Tomaten (Dose)', group: 'Konserven' },
      { id: 'si-057', amount: 200, unit: 'ml', name: 'Kokosmilch', group: 'Konserven' },
      { id: 'si-058', amount: 2, unit: 'EL', name: 'Tomatenmark', group: 'Konserven' },
      { id: 'si-059', amount: 2, unit: 'EL', name: 'Pflanzenöl', group: 'Öle & Essig' },
      { id: 'si-060', amount: 1, unit: 'Bund', name: 'frischer Koriander', group: 'Gemüse' },
      { id: 'si-061', amount: 300, unit: 'g', name: 'Basmati-Reis', group: 'Nudeln & Reis' },
    ],
    steps: [
      { id: 'ss-050', order: 1, title: 'Hähnchen marinieren', text: 'Hähnchenbrustfilet in mundgerechte Stücke schneiden. Mit Joghurt und 1 TL Tikka-Masala-Gewürz vermischen. Mindestens 30 Minuten (besser über Nacht) marinieren.', timer_min: 30 },
      { id: 'ss-051', order: 2, title: 'Hähnchen anbraten', text: 'Öl in einer Pfanne erhitzen. Hähnchen portionsweise scharf anbraten, bis es gebräunt ist. Beiseitestellen.', timer_min: 8 },
      { id: 'ss-052', order: 3, title: 'Aromaten anschwitzen', text: 'Zwiebeln in derselben Pfanne goldbraun braten. Fein gehackten Knoblauch und Ingwer hinzufügen und 2 Minuten mitbraten.', timer_min: 7 },
      { id: 'ss-053', order: 4, title: 'Sauce kochen', text: 'Tomatenmark und restliche Gewürze einrühren. Stückige Tomaten und Kokosmilch angießen. 15 Minuten köcheln lassen.', timer_min: 15 },
      { id: 'ss-054', order: 5, title: 'Hähnchen einlegen', text: 'Gebratenes Hähnchen zurück in die Sauce geben. Weitere 10 Minuten köcheln bis alles gar und die Sauce eingedickt ist.', timer_min: 10 },
      { id: 'ss-055', order: 6, title: 'Reis kochen & servieren', text: 'Basmati-Reis nach Packungsanweisung kochen. Curry mit frischem Koriander garnieren und mit dem Reis servieren.' },
    ],
    created_at: '2024-06-30T18:00:00.000Z',
    updated_at: '2024-06-30T18:00:00.000Z',
  },
];
